// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kuywnjgjdtmajaellmmr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1eXduamdqZHRtYWphZWxsbW1yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MzYwOTUsImV4cCI6MjA3MDQxMjA5NX0.nWDPXdC27u7snMkmU9vW3joB4U7lZkIooN5hKw3Wmvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});